<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
<!ELEMENT root (results|texts)*>
<!ELEMENT texts (#PCDATA)>
<!ATTLIST texts name ID #REQUIRED value CDATA "default">
<!ATTLIST texts separator CDATA #IMPLIED>
]>

<root>
    <!-- Expressions à analyser et tester -->
  <texts name="exprs"><![CDATA[",
      "17+b", "n*2", "2n", "3*(17+b)",
      "a+3*(17+b)", "32", "3-7",
      "m+5",
      "1+2+3",
      "3*2", "3*i", "3*x",
      "3*x+2", "2+3*x",
      "x^4",
      "3*x^4",
      "3*x^4+2*x",
      "3-7", "a+8-41", "3/4", "5*a", "3^2",
      "SQR(2)", "SQR(2)+1", "3+(1+2)",
      "(1+2)*b", "3*a-7", "(1+2)*(b+a)",
      "6-3+7", "6-3*9+7",
      "a+3*(17+b)", "3*x^4-2*x+7",
      "2+|x-3|", "|a+5|-|3+2*x|",
      "3*(1+2*(x-b)^2)-(a+4)",
      "PGCD(6,4)", "PGCD((2+3),4)",
      "]]>
  </texts>
  <!-- Ecriture cmprenant les types correspondant à la méthode toText()  -->
  <texts name="complete"><![CDATA[",
      "(ADD,17:natural,b:real):real", "(MUL,n:natural,2:natural):natural", 
      "(MUL,2:natural,n:natural):natural",
      "(MUL,3:natural,(ADD,17:natural,b:real):real):real",
      "(ADD,a:real,(MUL,3:natural,(ADD,17:natural,b:real):real):real):real", "32:natural",
      "(SUB,3:natural,7:natural):integer",
      "(ADD,m:natural,5:natural):natural",
      "(ADD,(ADD,1:natural,2:natural):natural,3:natural):natural",
      "(MUL,3:natural,2:natural):natural", "(MUL,3:natural,i:integer):integer", "(MUL,3:natural,x:real):real",
      "(ADD,(MUL,3:natural,x:real):real,2:natural):real", "(ADD,2:natural,(MUL,3:natural,x:real):real):real",
      "(POW,x:real,4:natural):real",
"]]>      
  </texts>
  <!-- Ecriture correspondant à la méthode toString()  -->
  <texts name="results"><![CDATA[",
      "(ADD,17,b)", "(MUL,n,2)", "(MUL,2,n)",
      "(MUL,3,(ADD,17,b))",
      "(ADD,a,(MUL,3,(ADD,17,b)))", "32", "(SUB,3,7)",
      "(ADD,m,5)",
      "(ADD,(ADD,1,2),3)",
      "(MUL,3,2)", "(MUL,3,i)", "(MUL,3,x)",
      "(ADD,(MUL,3,x),2)", "(ADD,2,(MUL,3,x))",
      "(POW,x,4)",
      "(MUL,3,(POW,x,4))",
      "(ADD,(MUL,3,(POW,x,4)),(MUL,2,x))",
      "(SUB,3,7)", "(SUB,(ADD,a,8),41)", "(DIV,3,4)", "(MUL,5,a)", "(POW,3,2)",
      "(SQR,2)", "(ADD,(SQR,2),1)", "(ADD,3,(ADD,1,2))",
      "(MUL,(ADD,1,2),b)", "(SUB,(MUL,3,a),7)", "(MUL,(ADD,1,2),(ADD,b,a))",
      "(ADD,(SUB,6,3),7)", "(ADD,(SUB,6,(MUL,3,9)),7)",
      "(ADD,a,(MUL,3,(ADD,17,b)))", "(ADD,(SUB,(MUL,3,(POW,x,4)),(MUL,2,x)),7)",
      "(ADD,2,(ABS,(SUB,x,3)))", "(SUB,(ABS,(ADD,a,5)),(ABS,(ADD,3,(MUL,2,x))))",
      "(SUB,(MUL,3,(ADD,1,(MUL,2,(POW,(SUB,x,b),2)))),(ADD,a,4))",
      "(PGCD,6,4)", "(PGCD,(ADD,2,3),4)",
      "(LT,3,4)",
      "(LE,(ADD,3,5),(MUL,3,x))",
      "(OR,(LT,3,5),(GE,2,3))", "(AND,(LT,a,8),(GE,a,3))",
      "(IMPLIES,(AND,(LT,a,8),(GE,a,3)),(LT,a,9))",
      "(AND,(EQU,a,3),(LT,a,9))", "(AND,(LT,a,8),(OR,(EQU,a,3),(LT,a,9)))",
      "(SUB,7)", "(ADD,(SUB,2),7)", "(SUB,(ADD,3),2)", "(SUB,3,(ADD,2))",
      "(ABS,(MUL,6,8))", "(ADD,2,(MUL,3,4))", "(SUB,(DIV,3,a),(MUL,a,47))",
      "(SUB,(DIV,3,a),(MUL,(ADD,a,2),47))",
      "(NOT,(LT,x,3))", "(IMPLIES,(NOT,(EQU,x,3)),(OR,(LT,x,3),(GT,x,3)))",
      "(SUB,3,(ABS,(SUB,3,2)))",
      "(SET,a,b,3)", "(CI,3,7)", "(OI,(ADD,3,4),a)",
      "(SEQ,1,2,3)", "(SEQ,1,(SEQ,2,3),(SEQ,4,6),EMPTYSET,(SET,a,1))",
      "(SEQ,5,(CI,2,8))", "(SEQEXP,(SUB,3,(MUL,4,(POW,x,2))),(SUB,x,1),2)",
      "(EQUIV,(LT,x,2),(GT,2,x))",
      "(IN,3,(CI,0,4))", "(UNION,(SET,3,4),(SET,1,7))", "(PART,(SET,n,(ADD,n,2)),NATURAL)",
      "(PROD,NATURAL,NATURAL)", "(COMPL,NATURAL)",
      "(MUL,2,x)", "(ADD,(SUB,2),7)",
      "(ADD,(SUB,2,8),1)",
      "(DIFF,NATURAL,(SET,0))", "ABS : non valide, pas de nom",
      "(IN,x,NATURAL)", "(FORALL,x,(IN,x,NATURAL))", "(FORALL,y,(FORALL,x,(AND,(IN,x,NATURAL),(EQU,x,y))))",
      "(MUL,3,(POW,x,4))",
      "(SEQEXP,(ADD,x,1),(LT,2,8))",
      "(ADD,(MUL,2,9),(MUL,4,x))",
      "(MUL,(ADD,5,2),9)",
      "(ADD,(MUL,(ADD,5,2),9),(MUL,4,3))",
      "(ADD,(MUL,(ADD,3,2),9),(MUL,4,x))",
      "ADD(5,1,) : non valide, modèle non trouvé",
      "ADD(1,2,3,4) : non valide, modèle non trouvé",
      "(SUB,(MUL,4,(POW,x,2)),(ADD,x,2))",
 "]]>
  </texts>
  <texts name="replace"><![CDATA[",
    "a", "a=b-5", "b-5",
    "a+3×(17+b)", "a=b-5,b=2*x", "b-5+3*(17+2*x)",
    "5×x-2*y", "x=x+y,y=3", "5*(x+y)-2*3",
    "]]>
  </texts>
  <texts name="depth"><![CDATA[",
    "a", "1", "b-5", "2", "3×(17+b)", "3",
    "a+3×(17+b)", "4", "b-5+3*(17+2*x)", "5",
    "]]>
  </texts>
  <texts name="matches"><![CDATA[",
    "A B C",
    "a+3×(17+b)", "A+B", "var", "real",
    "2*(i+j)", "A*B", "var", "integer",
    "3×((m+4)^2-(m+4))", "A*(B^C-B)", "var", "real",
    "]]>
  </texts>
  <texts name="matchsubExpr" separator=":"><![CDATA[",
    "A B C D E F",
    "a-3×(17+b)", "C×(A+B):C×A+C×B", "var", "real", "a-(3×17+3×b)",
    "2*(i+j)", "C×(A+B):C×A+C×B", "var", "integer", "2*i+2*j",
    "3×((m+4)^2-(m+4))", "A-(B+C):A-B-C", "var", "real", "3×((m+4)^2-m-4)",
    "a(x+2)-b(y+b)", "C×(A+B):C×A+C×B", "var", "real", "a*x+a*2-(b*y+b*b)",
    "a-3+x", "C×(A+B):C×A+C×B", "var", "real", "a-3+x",
    "]]>
  </texts>
  <texts name="matchBoth"><![CDATA[",
    "A B C",
    "A+3×(17+b)", "(c-d)+B", "var", "real",
    "2*(i+j)", "A*B", "var", "integer",
    "A*(B+C)", "(A+C)*B", "var", "integer",
    "]]>
  </texts>
  <!-- sortie des expressions par la méthode toString(syntaxWrite) -->
  <texts name="write_numbers"><![CDATA[",
      "17+b", "n×2", "2×n", "3×(17+b)",
      "a+3×(17+b)", "32", "3-7",
      "m+5",
      "1+2+3",
      "3×2", "3×i", "3×x",
      "3×x+2", "2+3×x",
      "x^4",
      "3×x^4",
      "3×x^4+2×x",
      "3-7", "a+8-41", "3/4", "5×a", "3^2",
      "SQR(2)", "SQR(2)+1", "3+(1+2)",
      "(1+2)×b", "3×a-7", "(1+2)×(b+a)",
      "6-3+7", "6-3×9+7",
      "a+3×(17+b)", "3×x^4-2×x+7",
      "2+|x-3|", "|a+5|-|3+2×x|",
      "3×(1+2×(x-b)^2)-(a+4)",
      "]]>
  </texts>
</root>
