<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
<!ELEMENT root (syntax)*>
<!ATTLIST syntax file ID #REQUIRED>
<!ELEMENT syntax (texts)*>
<!ELEMENT texts (#PCDATA)>
<!ATTLIST texts name CDATA #REQUIRED>
<!ATTLIST texts separator CDATA #IMPLIED>
]>

<root>
  <syntax file="number_syntax.syx">
  <texts name="matches"><![CDATA[",
    "x y z",
    "a+3×(17+b)", "x+y", "var", "real",
    "2*(i+j)", "x*y", "var", "integer",
    "3×((m+4)^2-(m+4))", "x*(y^z-y)", "var", "real",
    "]]>
  </texts>
  <texts name="matchBoth"><![CDATA[",
    "x y z",
    "x+3×(17+b)", "(c-d)+y", "var", "real",
    "2*(i+j)", "x*y", "var", "integer",
    "x*(y+z)", "(x+z)*y", "var", "integer",
    "]]>
  </texts>
  <texts name="matchsubExpr" separator=":"><![CDATA[",
    "x y z D E F",
    "a-3×(17+b)", "z×(x+y):z×x+z×y", "var", "real", "a-(3×17+3×b)",
    "2*(i+j)", "z×(x+y):z×x+z×y", "var", "integer", "2*i+2*j",
    "3×((m+4)^2-(m+4))", "x-(y+z):x-y-z", "var", "real", "3×((m+4)^2-m-4)",
    "a(x+2)-b(y+b)", "z×(x+y):z×x+z×y", "var", "real", "a*x+a*2-(b*y+b*b)",
    "a-3+x", "z×(x+y):z×x+z×y", "var", "real", "a-3+x",
    "]]>
  </texts>
  </syntax>
  <syntax file="prop_syntax.syx">    
  </syntax>
</root>
